<?php

echo "
Para usar bloco de codigo basta inserir no post onde o bloco começando por<br>
;;lang=[escolha]<br>
<br>
onde [escolha] é uma das nomeclaturas das linguagens abaixo citadas:<br>

<br>
Markup - ;;lang=markup<br>
CSS - ;;lang=css<br>
C-like - clike
JavaScript - ;;lang=javascript<br>
ABAP - ;;lang=abap<br>
ActionScript - ;;lang=actionscript<br>
Ada - ;;lang=ada<br>
Apache Configuration - ;;lang=apacheconf<br>
APL - ;;lang=apl<br>
AppleScript - ;;lang=applescript<br>
Arduino - ;;lang=arduino<br>
ARFF - ;;lang=arff<br>
AsciiDoc - ;;lang=asciidoc<br>
6502 Assembly - ;;lang=asm6502<br>
ASP.NET (C#) - ;;lang=aspnet<br>
AutoHotkey - ;;lang=autohotkey<br>
AutoIt - ;;lang=autoit<br>
Bash - ;;lang=bash<br>
BASIC - ;;lang=basic<br>
Batch - ;;lang=batch<br>
Bison - ;;lang=bison<br>
Brainfuck - ;;lang=brainfuck<br>
Bro - ;;lang=bro<br>
C - ;;lang=c<br>
C# - ;;lang=csharp<br>
C++ - ;;lang=cpp<br>
CoffeeScript - ;;lang=coffeescript<br>
Clojure - ;;lang=clojure<br>
Crystal - ;;lang=crystal<br>
Content-Security-Policy - ;;lang=csp<br>
CSS Extras - css-;;lang=extras<br>
D - ;;lang=d<br>
Dart - ;;lang=dart<br>
Diff - ;;lang=diff<br>
Django/Jinja2 - ;;lang=django<br>
Docker - ;;lang=docker<br>
Eiffel - ;;lang=eiffel<br>
Elixir - ;;lang=elixir<br>
Elm - ;;lang=elm<br>
ERB - ;;lang=erb<br>
Erlang - ;;lang=erlang<br>
F# - ;;lang=fsharp<br>
Flow - ;;lang=flow<br>
Fortran - ;;lang=fortran<br>
GEDCOM - ;;lang=gedcom<br>
Gherkin - ;;lang=gherkin<br>
Git - ;;lang=git<br>
GLSL - ;;lang=glsl<br>
Go - ;;lang=go<br>
GraphQL - ;;lang=graphql<br>
Groovy - ;;lang=groovy<br>
Haml - ;;lang=haml<br>
Handlebars - ;;lang=handlebars<br>
Haskell - ;;lang=haskell<br>
Haxe - ;;lang=haxe<br>
HTTP - ;;lang=http<br>
HTTP Public-Key-Pins - ;;lang=hpkp<br>
HTTP Strict-Transport-Security - ;;lang=hsts<br>
IchigoJam - ;;lang=ichigojam<br>
Icon - ;;lang=icon<br>
Inform 7 - ;;lang=inform7<br>
Ini - ;;lang=ini<br>
Io - ;;lang=io<br>
J - ;;lang=j<br>
Java - ;;lang=java<br>
Jolie - ;;lang=jolie<br>
JSON - ;;lang=json<br>
Julia - ;;lang=julia<br>
Keyman - ;;lang=keyman<br>
Kotlin - ;;lang=kotlin<br>
LaTeX - ;;lang=latex<br>
Less - ;;lang=less<br>
Liquid - ;;lang=liquid<br>
Lisp - ;;lang=lisp<br>
LiveScript - ;;lang=livescript<br>
LOLCODE - ;;lang=lolcode<br>
Lua - ;;lang=lua<br>
Makefile - ;;lang=makefile<br>
Markdown - ;;lang=markdown<br>
Markup templating - markup-;;lang=templating<br>
MATLAB - ;;lang=matlab<br>
MEL - ;;lang=mel<br>
Mizar - ;;lang=mizar<br>
Monkey - ;;lang=monkey<br>
N4JS - ;;lang=n4js<br>
NASM - ;;lang=nasm<br>
nginx - ;;lang=nginx<br>
Nim - ;;lang=nim<br>
Nix - ;;lang=nix<br>
NSIS - ;;lang=nsis<br>
Objective-C - ;;lang=objectivec<br>
OCaml - ;;lang=ocaml<br>
OpenCL - ;;lang=opencl<br>
Oz - ;;lang=oz<br>
PARI/GP - ;;lang=parigp<br>
Parser - ;;lang=parser<br>
Pascal - ;;lang=pascal<br>
Perl - ;;lang=perl<br>
PHP - ;;lang=php<br>
PHP Extras - php-;;lang=extras<br>
PL/SQL - ;;lang=plsql<br>
PowerShell - ;;lang=powershell<br>
Processing - ;;lang=processing<br>
Prolog - ;;lang=prolog<br>
.properties - ;;lang=properties<br>
Protocol Buffers - ;;lang=protobuf<br>
Pug - ;;lang=pug<br>
Puppet - ;;lang=puppet<br>
Pure - ;;lang=pure<br>
Python - ;;lang=python<br>
Q (kdb+ database) - ;;lang=q<br>
Qore - ;;lang=qore<br>
R - ;;lang=r<br>
React JSX - ;;lang=jsx<br>
React TSX - ;;lang=tsx<br>
Ren'py - ;;lang=renpy<br>
Reason - ;;lang=reason<br>
reST (reStructuredText) - ;;lang=rest<br>
Rip - ;;lang=rip<br>
Roboconf - ;;lang=roboconf<br>
Ruby - ;;lang=ruby<br>
Rust - ;;lang=rust<br>
SAS - ;;lang=sas<br>
Sass (Sass) - ;;lang=sass<br>
Sass (Scss) - ;;lang=scss<br>
Scala - ;;lang=scala<br>
Scheme - ;;lang=scheme<br>
Smalltalk - ;;lang=smalltalk<br>
Smarty - ;;lang=smarty<br>
SQL - ;;lang=sql<br>
Soy (Closure Template) - ;;lang=soy<br>
Stylus - ;;lang=stylus<br>
Swift - ;;lang=swift<br>
TAP - ;;lang=tap<br>
Tcl - ;;lang=tcl<br>
Textile - ;;lang=textile<br>
Template Toolkit 2 - ;;lang=tt2<br>
Twig - ;;lang=twig<br>
TypeScript - ;;lang=typescript<br>
VB.Net - ;;lang=vbnet<br>
Velocity - ;;lang=velocity<br>
Verilog - ;;lang=verilog<br>
VHDL - ;;lang=vhdl<br>
vim - ;;lang=vim<br>
Visual Basic - visual-;;lang=basic<br>
WebAssembly - ;;lang=wasm<br>
Wiki markup - ;;lang=wiki<br>
Xeora - ;;lang=xeora<br>
Xojo (REALbasic) - ;;lang=xojo<br>
XQuery - ;;lang=xquery<br>
YAML - ;;lang=yaml<br;;lang=>
<br>
";
